### ISSUE TITLE
browse_remote

### ISSUE THREAD

**Issue by gertcuykens** [eagletmt/unite-haddock#1]
Can not figure out how to use browse_remote instead of browse_local in vim?

```
:Unite haddock
```

**Comment by eagletmt** [comment]
Press `<Plug>(unite_choose_action)` (default: `<Tab>`) on a candidate in the unite buffer to choose an action.
You can change the default action by `unite#custom_default_action()`.

``` vim
call unite#custom_default_action('haddock', 'browse_remote')
```

**Comment by gertcuykens** [comment]
ok thx works :)

**Comment by gertcuykens** [comment]
ps would a setting like `let g:unite_haddock_default_action='browse_remote'` be nicer?

**Comment by eagletmt** [comment]
No. Setting a default action is unite.vim's job and I don't think unite sources should provide another way for it.
Instead, I will add a notice about how to change the default action of haddock.

**Comment by gertcuykens** [comment]
ok thanks
